# Generated by Django 4.1.2 on 2023-05-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=25)),
                ('photo', models.ImageField(upload_to='')),
                ('email', models.CharField(max_length=25)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
